# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38e2fc939b541c665695ca6bca2e545ce748e44ed7c99f2025312e8051876e394ed69a59b0d42df4466df82f7212134fb838686dbedd02cd5cab21bacdc036f1

test:
  secret_key_base: 29c02a91ada1dca228deeb379c028271563ed3c51772d8a58e1ea959725de45754022486fb2722ea3d478618498de039ee949d9f732b6c233eeb927630020fc7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
